{% set python_min = "3.10" %}
{% set name = "graphrag" %}
{% set version = "2.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/graphrag-{{ version }}.tar.gz
  sha256: a6e60bda86e282aea892cddacd08f31f9c4bac0bc831efb53661096177df0239

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning >=1.0.0,<2.0.0
    - pip
  run:
    - azure-cosmos >=4.9.0
    - devtools >=0.12.2
    - fnllm >=0.4.1
    - litellm >=1.77.1
    - spacy >=3.8.4
    - textblob >=0.18.0.post0
    - tqdm >=4.67.1
    - typer >=0.16.0
    - typing_extensions >=4.12.2
    - matplotlib-base >=3.9.0,<4.0.0
    - pandas >=2.2.3,<3
    - pyarrow >=17.0.0
    - umap-learn >=0.5.6
    - future >=1.0.0
    - json-repair >=0.30.3
    - python >={{ python_min }},<3.13
    - environs >=11.0.0
    - datashaper >=0.0.49,<0.0.50
    - azure-search-documents >=11.5.2
    - lancedb >=0.17.0
    - uvloop >=0.20.0,<0.21.0
    - nest-asyncio >=1.6.0,<2.0.0
    - aiolimiter >=1.1.0,<2.0.0
    - aiofiles >=24.1.0
    - openai >=1.68.0
    - nltk ==3.9.1
    - tiktoken >=0.11.0
    - numba 0.60.0
    - numpy >=1.25.2
    - graspologic >=3.4.1
    - networkx >=3.4.2
    - fastparquet >=2024.2.0,<2025.0.0
    - scipy 1.12.0
    - pyyaml >=6.0.2
    - pyaml-env >=1.2.1,<2.0.0
    - python-dotenv >=1.0.1
    - tenacity >=9.0.0,<10.0.0
    - swifter >=1.4.0,<2.0.0
    - pydantic >=2.10.3
    - rich >=13.6.0,<14.0.0
    - textual >=0.78.0,<0.79.0
    - python-devtools >=0.12.2,<0.13.0
    - typing-extensions >=4.12.2,<5.0.0
    - azure-storage-blob >=12.24.0
    - azure-identity >=1.19.0

test:
  imports:
    - graphrag
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: A modular graph-based Retrieval-Augmented Generation (RAG) system
  home: https://github.com/microsoft/graphrag
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
